config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "photos#index"

  resources :photos do
    resources :comments
    member do
    put "like", to: "photos#upvote"
    put "dislike", to: "photos#downvote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, length: { minimum: 1 }
  belongs_to :user
  has_one :photo


end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :name, length: { minimum: 1 }, uniqueness: true
  has_attached_file :avatar, styles: { medium: "300x300>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord

  devise :omniauthable, :omniauth_providers => [:facebook]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name

   end
 end
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @photo = Photo.find(params[:photo_id])
    @comments = Comment.where(photo_id: params[:photo_id])
    @image_url = @photo.avatar.url(:medium)
  end

  def new
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.new
  end

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to photo_comments_path
      flash[:notice] = "Comment added!"
    else
      redirect_to new_photo_comment_path
      flash[:alert] = "Sorry you cannot add an empty comment"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @photo = Photo.find(params[:photo_id])
  end

  def update
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to photo_comments_path
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to photo_comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

before_action :authenticate_user!, :except => [:index, :show]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(photo_params)
    @photo.user = current_user
    if @photo.save
      redirect_to photos_path
      flash[:notice] = "Photo successfully uploaded!"
    else
      render "new"
      flash[:alert] = "Sorry, you must uploaded a valid photo with a valid name"
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comments = Comment.where(photo_id: params[:photo_id])
    @image_url = @photo.avatar.url(:medium)
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)
    redirect_to photo_path
  end

  def destroy
    @photo = Photo.find(params[:id])
    if current_user.id == @photo.user.id
      @photo.destroy
      flash[:notice] = "Photo deleted!"
      redirect_to photos_path
    end
  end

  def upvote
    @photo = Photo.find(params[:id])
    @photo.upvote_by current_user
    redirect_to root_path
  end

  def downvote
    @photo = Photo.find(params[:id])
    @photo.downvote_by current_user
    redirect_to root_path
  end

  private

  def photo_params
    params.require(:photo).permit(:name, :description, :avatar)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/application/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <h1>Pict</h1>
    <h4>Share your experiences</h4>
</head>

app/views/comments/edit.html.erb
<div class="container">

    <h2>Edit your comment</h2>
    <br>



  <%= form_for [@photo, @comment] do |f| %>
  <div class="form-group row">
    <label for="name" class="col-xs-2 col-form-label"><%= f.label :comment %></label>
       <div class="col-xs-10" id="name" placeholder="Edit photo name">
         <%= f.text_field :comment, class: 'form-control' %>
       </div>
     </div>
      <%= f.hidden_field :photo_id, value: @photo.id %>
      <p><%= f.submit %></p>
      <p><button><%= link_to "Delete comment", photo_comment_path(@photo, @comment), method: :delete %></button></p>
  <% end %>
</div>

app/views/comments/index.html.erb
<div class="container">

  <h2>Comments</h2>
  <div class="panel panel-default">
    <div class="panel-heading">
  <h4><%= link_to "#{@photo.name}", photo_path(@photo) %></h4>
</div>
  <div class="panel-body">
  <p><b>Description</b></p>
    <p><%= @photo.description %></p>
    <p><%= image_tag(@image_url) %></p>

  <% if @comments.any? %>
    <% @comments.each do |comment| %>
      <p>Comment: <%=comment.comment%> <p>
        <% if current_user && current_user.id == comment.user_id %>
      <small><%= link_to "Edit #{comment.comment}", edit_photo_comment_path(@photo, comment) %></small>
      <% end %>
    <% end %>
    <% else %>
  </div>
    <h1>No comments yet!</h1>
    <% end %>
  </div>

app/views/comments/new.html.erb
<div class="container">

    <h2>Add comment!</h2>
    <br>
  <%= form_for [@photo, @comment], url: photo_comments_path do |f| %>
  <div class="form-group row">
    <label for="name" class="col-xs-2 col-form-label"><%= f.label :comment %></label>
       <div class="col-xs-10" id="name" placeholder="Edit photo name">
         <%= f.text_field :comment, class: 'form-control' %>
       </div>
     </div>
      <p><%= f.submit %></p>
      <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <%= csrf_meta_tags %>
     <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" type="text/css">
  </head>
  <body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
            <span class="glyphicon glyphicon-camera"></span>
          </a>
        </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <% if user_signed_in? %>
              <li><%= link_to "Signed in as: #{current_user.email}", edit_user_registration_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
               <li><a href="/photos/new">Upload photos</a></li>
               <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <% if notice %>
            <div class="alert alert-success" id="notice">
              <span class="glyphicon glyphicon-info-sign"></span> <%= notice %>
            </div>
          <% end %>

          <% if alert %>
            <div class="alert alert-danger" id="alert">
              <span class="glyphicon glyphicon-exclamation-sign"></span> <%= alert %>
            </div>
          <% end %>
      <%= yield %>
    </body>
</html>

app/views/photos/edit.html.erb
<div class="container">

    <h2>Edit photo details below</h2>
    <br>



  <%= form_for @photo do |f| %>
  <div class="form-group row">
    <label for="name" class="col-xs-2 col-form-label"><%= f.label :name %></label>
       <div class="col-xs-10" id="name" placeholder="Edit photo name">
         <%= f.text_field :name, class: 'form-control' %>
       </div>
     </div>
     <div class="form-group row">
       <label for="description" class="col-xs-2 col-form-label"><%= f.label :description %></label>
         <div class="col-xs-10" id="description">
         <%= f.text_field :description, class: 'form-control' %>
       </div>
     </div>
    <p>  <%= f.file_field :avatar %></p>
      <p><%= f.submit %></p>
      <% if (current_user.id == @photo.user_id)%>
        <p><%= link_to "Delete #{@photo.name}", photo_path(@photo), method: :delete %></p>
        <% end %>
  <% end %>
</div>

app/views/photos/index.html.erb
<!DOCTYPE HTML>

<div class="container">
<head>
  <h1>Pict</h1>

  <h4>Share your experiences!</h4>
</head>

<% if @photos.any? %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b><%= link_to "#{photo.name}", photo_path(photo)%></b>
      </div>
  <div class="panel-body">
    <p> <%= photo.description %></p>
    <p><%= image_tag(photo.avatar.url(:medium)) %></p>
    <p><%= link_to like_photo_path(photo), method: :put do %>
      <button id="like" type="button" class="like">
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
      <%= photo.get_upvotes.size %>
    </button>
    <% end %>
  </p>
    <p>
      <%= link_to dislike_photo_path(photo), method: :put do %>
        <button id="dislike" type="button" class="dislike">
          <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
        <%= photo.get_downvotes.size %>
          </button>
        <% end %>
      </p>
      </div>
    </div>
  <% end %>
  <% else %>
  <h1>No photos yet!</h1>
  <% end %>
</div>

app/views/photos/new.html.erb
<!DOCTYPE html>

<div class="container">

<h1>Share your expereinces</h1>
<br>

<%= form_for(@photo, html: {multipart: true}) do |f| %>
<div class="form-group row">
  <label for="name" class="col-xs-2 col-form-label">  <%= f.label :name %></label>
    <div class="col-xs-10" id="name">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <label for="name" class="col-xs-2 col-form-label">  <%= f.label :description %></label>
      <div class="col-xs-10" id="name">
        <%= f.text_field :description, class: 'form-control' %>
      </div>
    </div>
  <p><%= f.file_field :avatar %></p>
  <p><%= f.submit(class: "btn btn-primary") %></p>
  <% end %>
</div>

app/views/photos/show.html.erb
<!DOCTYPE html>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
          <h4><%= @photo.name %></h4>
        </div>
        <div class="panel-body">
          <p><b>Description</b></p>
            <p><%= @photo.description %></p>
          <p><%= image_tag(@image_url) %></p>
        </div>
        <div class="panel-footer">
          <% if current_user && current_user.id == @photo.user_id %>
            <%= link_to "Edit #{@photo.name}", edit_photo_path(@photo) %>
          <% end %>
          <%= link_to "Add comment", new_photo_comment_path(@photo) %>
          <%= link_to "View comments", photo_comments_path(@photo) %>
        </div>
      </div>
    </div>